package orm;

public class MybatisGeneratorjavaUserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.ID
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.USERNAME
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.PASSWORD
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.ID
     *
     * @return the value of SCOTT.MYBATIS_GENERATORJAVA_USERINFO.ID
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.ID
     *
     * @param id the value for SCOTT.MYBATIS_GENERATORJAVA_USERINFO.ID
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.USERNAME
     *
     * @return the value of SCOTT.MYBATIS_GENERATORJAVA_USERINFO.USERNAME
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.USERNAME
     *
     * @param username the value for SCOTT.MYBATIS_GENERATORJAVA_USERINFO.USERNAME
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.PASSWORD
     *
     * @return the value of SCOTT.MYBATIS_GENERATORJAVA_USERINFO.PASSWORD
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.MYBATIS_GENERATORJAVA_USERINFO.PASSWORD
     *
     * @param password the value for SCOTT.MYBATIS_GENERATORJAVA_USERINFO.PASSWORD
     *
     * @mbggenerated Tue May 17 16:48:30 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }
}