/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.emind.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.emind.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-07-2015
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" scope="request"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		if("123".equalsIgnoreCase(userForm.getPassword())){
			return mapping.findForward("ok");
		}
		else{
			return mapping.findForward("error");
		}
	}
}